services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - resume-optimizer-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/resume_optimizer
      - PORT=5000
    networks:
      - resume-optimizer-network

networks:
  resume-optimizer-network:
    driver: bridge

volumes:
  mongodb_data:
